### ISSUE TITLE
"Error: Cannot find module 'jsdom'" during first `npm test`

### ISSUE THREAD

**Issue by gregoryruiz** [alexvictoor/react-tdd-handson#5]
FYI I had to `npm i jsdom --save-dev` in order first `npm test` not to throw exception.
- npm -v 3.10.3
- node -v 6.7.0

**Comment by alexvictoor** [comment]
really strange, enzyme via cheerio has a dependency on it:

enzyme@2.4.1 node_modules/enzyme
├── is-subset@0.1.1
├── object-is@1.0.1
├── object.assign@4.0.4 (function-bind@1.1.0, object-keys@1.0.11, define-properties@1.1.2)
├── object.values@1.0.3 (has@1.0.1, function-bind@1.1.0, define-properties@1.1.2, es-abstract@1.6.1)
├── cheerio@0.20.0 (entities@1.1.1, dom-serializer@0.1.0, css-select@1.2.0, htmlparser2@3.8.3, jsdom@7.2.2)
└── lodash@4.16.4

**Comment by alexvictoor** [comment]
thanks!
problem reproduced on travisci
